name: Commitizen

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    bump_version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Bump and changelog using commitizen
              uses: commitizen-tools/commitizen-action@0.20.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  commit: true
                  push: true
