name: Prepare release
on:
    push:
        branches: ['main']
jobs:
    prepare_release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: main
                  token: ${{ secrets.GIT_ACCESS_TOKEN }}
            - name: Deps
              run: npm ci
            - name: Tests
              run: npm run test:coverage
            - name: Generating coverage badges
              uses: jpb06/jest-badges-action@latest
              with:
                  branches: main
                  no-commit: true
            - name: Bump and changelog using commitizen
              run: |
                  git add badges
                  git config --local user.email "github-actions@github.com"
                  git config --local user.name "github-actions"
                  npm run version:bump
