name: Prepare release
on:
    push:
        branches: ['main']
jobs:
    prepare_release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Deps
              run: npm ci
            - name: Tests
              run: npm run test:coverage
            - name: Generating coverage badges
              uses: jpb06/jest-badges-action@latest
              with:
                  branches: main
            - name: Bump and changelog using commitizen
              uses: commitizen-tools/commitizen-action@0.20.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  commit: true
                  push: true
