name: Release (first)
on: workflow_dispatch

jobs:
    release_first:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: main
                  token: ${{ secrets.GIT_ACCESS_TOKEN }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Configure git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            - run: npm ci
            - run: npm run test:coverage
            - run: NODE_ENV=production npm run build
            - name: Generating coverage badges
              uses: jpb06/jest-badges-action@latest
              with:
                  branches: main
                  no-commit: true
            - run: git add badges
            - run: npm run version:bump -- --first-release
            - name: Push to GitHub
              run: |
                  git push -f
                  git push --tags
                  echo "TAG_NAME=$(git describe)" >> "$GITHUB_ENV"
            - name: Publish to NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
            - name: GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  draft: false
                  body_path: CHANGELOG.md
                  name: ${{env.TAG_NAME}}
                  tag_name: ${{env.TAG_NAME}}
